#!/usr/bin/env bash
# Display information about subdomains.

# Function to retrieve and display info about a subdomain
domain_information () {
	#DNS lookup
	line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	#Extract and print info
	echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check the number of arguments passed to the script
if [ "$#" == 1 ]
then 
	#if one argument
	domain_information "$1" "www"
	domain_information "$1" "lb-01"
	domain_information "$1" "web-01"
	domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then 
	#if two arguments
	domain_information "$1" "$2"
fi
